name: milestone_4
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  dio: 5.4.2+1
  json_serializable: 6.7.1
  json_annotation: 4.8.1
  hive: 2.2.3
  hive_flutter: 1.1.0
  get: 4.6.6
  google_fonts: 6.2.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  hive_generator: 2.0.1
  build_runner: 2.4.9
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

